name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: ${{ matrix.os }}-py3.8
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          conda install flake8=3.8.4 black=22.3.0
          echo "flake8 version =" $(flake8 --version)
          echo "black version =" $(black --version)
      - name: Flake8 formatting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --statistics
      - name: Black formatting
        run: |
          black --line-length=79 --check .
